name: Laravel

on: [push]

jobs:
  laravel-tests-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Move env file
        run: mv .env.testing .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run migrations
        run: php artisan migrate:fresh --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
      - name: Add ssh key
          run: cat ./.github/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
      - name: Run deployment
        run: |
          php artisan -v deploy:run deploy:unlock production -n -v
          php artisan -v deploy production -n -v
